version: "3.3"

services:
    traefik:
        image: traefik:v2.4
        container_name: traefik
        command:
            - "--global.checknewversion=false"
            - "--global.sendanonymoususage=false"
            - "--log=true"
            - "--log.level=ERROR"
            - "--entrypoints.http=true"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.http.http.redirections.entrypoint.to=https"
            - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.https=true"
            - "--entrypoints.https.address=:443"
            - "--certificatesresolvers.letsencrypt"
            - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
            - "--providers.docker"
            - "--providers.docker.watch=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=web"
        ports:
            - 80:80
            - 443:443
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${PERSISTENT_DIR}/acme.json:/acme.json
        networks:
            - web
        restart: unless-stopped

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        command: --schedule "0 0 4 * * 6" --label-enable --cleanup
        environment:
            - TZ=${TZ}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        restart: unless-stopped

    # whoami:
    #     image: traefik/whoami
    #     container_name: whoami
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.whoami.entrypoints=https"
    #         - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_BASE}`)"
    #         - "traefik.http.routers.whoami.tls=true"
    #         - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
    #         - "traefik.http.routers.whoami.tls.domains[0].main=whoami.${DOMAIN_BASE}"

    heimdall:
        image: linuxserver/heimdall:latest
        container_name: heimdall
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        volumes:
            - ${PERSISTENT_DIR}/heimdall/config:/config
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.heimdall.entrypoints=https"
            - "traefik.http.routers.heimdall.rule=Host(`${DOMAIN_BASE}`)"
            - "traefik.http.routers.heimdall.tls=true"
            - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"
            - "traefik.http.routers.heimdall.tls.domains[0].main=${DOMAIN_BASE}"
            - "traefik.http.services.heimdall.loadbalancer.server.port=80"
            - "com.centurylinklabs.watchtower.enable=true"
        networks:
            - web
        restart: unless-stopped

networks: 
    web:
        external: true
