version: '3' 

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PERSISTENT_DIR}/proxy/conf.d:/etc/nginx/conf.d:rw
      - ${PERSISTENT_DIR}/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ${PERSISTENT_DIR}/proxy/html:/usr/share/nginx/html:rw
      - ${PERSISTENT_DIR}/proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    volumes:
      - ${PERSISTENT_DIR}/proxy/certs:/etc/nginx/certs:rw
      - ${PERSISTENT_DIR}/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ${PERSISTENT_DIR}/proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - ${PERSISTENT_DIR}/app/config:/var/www/html/config
      - ${PERSISTENT_DIR}/app/custom_apps:/var/www/html/custom_apps
      - ${PERSISTENT_DIR}/app/data:/var/www/html/data
      - ${PERSISTENT_DIR}/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=nextcloud.${DOMAIN_BASE}
      - LETSENCRYPT_HOST=nextcloud.${DOMAIN_BASE}
      - LETSENCRYPT_EMAIL=${ACME_EMAIL}
    restart: unless-stopped

  static:
    image: nginx:latest
    container_name: static
    depends_on: 
      - letsencrypt
      - proxy
    volumes:
      - ${PERSISTENT_DIR}/static/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=${DOMAIN_BASE}
    restart: unless-stopped

volumes:
  nextcloud:
  db:

